### ISSUE TITLE
Excess paperfeed when printing jpg from command line

### ISSUE THREAD

**Issue by R4C3R** [IntegersOfK/Hoin-POS-58-80#1]
Hi,

I've encountered an issue where the POS-58-Series shows unexpected behavior.

When I issue the following command from the command line:

`lpr -P POS-58-Series qrcode.jpg`

It prints the jpg (a QR-Code) but not after it has added ca 86mm of white space before actually starting to print the jpg, which creates a lot of paperwaste.

The jpg has the following characteristics according to imagemagick:

qrcode.jpg JPEG 123x123 123x123+0+0 8-bit Gray 256c 8.3KB 0.000u 0:00.010

I am not using any headers or footers, regular text files are not printed with any additional white space.

**Comment by R4C3R** [comment]
I found what caused the problem. By default CUPS centers an image on the page. In this case the page is defined in CUPS as 58mm x 210mm.

when using the command line option `-o position=top` then the image is correctly printed and no extra white space is added before the image.

**Comment by IntegersOfK** [comment]
Right on! I was wondering about that myself, so thank you for sharing your problem and solution.
