### ISSUE TITLE
Build for MacOS

### ISSUE THREAD

**Issue by ytbryan** [IntegersOfK/Hoin-POS-58-80#2]
Hi there, 

Thanks for this repo. I wonder, have you built the filter for 58mm for MacOS? 

I'm stuck at getting it work with CUPs on macOS. The filter failed.

**Comment by IntegersOfK** [comment]
No sorry I don't have access to a Mac but if you get it working please let others know because this seems to be a popular printer and repo. Or submit a pull request, thanks good luck!

**Comment by ytbryan** [comment]
Recently, I discovered http://gimp-print.sourceforge.net. But hion isn't supported. When I have time, I will give them a try to see if other drivers will work well with the hion printer. 

If anyone reading this, has tried the Gutenprint printer on hion printer, please share the details. thanks!
