### ISSUE TITLE
Compatibility with CUPS 2.2.5

### ISSUE THREAD

**Issue by crudolf** [IntegersOfK/Hoin-POS-58-80#3]
If I compile the file using latest CUPS I get following issues:

ppd_file_t undeclared

I am trying to make the filter compiling for MacOS. Do you have a clue what might be the issue? Is it, that the file is not made for latest CUPS or is MacOS missing the development libraries.

```
gcc -g -O2   -c -o rastertopos.o rastertopos.c
rastertopos.c:78:16: error: unknown type name 'ppd_file_t'; did you mean 'cups_file_t'?
void    StartPage(ppd_file_t *ppd, cups_page_header2_t *header);
                  ^~~~~~~~~~
                  cups_file_t
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/cups/file.h:60:29: note: 'cups_file_t' declared here
typedef struct _cups_file_s cups_file_t;/**** CUPS file type ****/
                            ^
```

**Comment by mckaygerhard** [comment]
i researh within the files and the files are not for recent CUPS, so whenatime due i are busy i recomended to use a older cups like my debian squeeze 1.X cups version

**Comment by shyaminayesh** [comment]
I just made a PR to fix this issue. It'll fix the issue for now and I'll do some clean up later.

@IntegersOfK
